export class Interview {
  id :number;
  type :string;
  nomProg :string;
  ideeProg :string;
  butProg :string;
  dureeProg :string;
  nomEvent :string;
  dateEvent :string;
  etabEvent :string;
  Autre :string;
  but :string;
  BenefBut :string;
  Budget: string;
  dirid : string;
  dirnom : string;
 diretat : string;
 dirdate : string;
 adminid : string;
 adminom : string;
 admietat : string;
 admidate : string;
 etabnom : string;
 etabid : string; 
 etabetat : string;
 etabdate : string;
  attribut1 :string;
  attribut2 :string;
  attribut3 :string;
  attribut4 :string;
  attribut5 :string;
  attribut6 :string;
  dateenreg :string;
  userNameCreator :string;
  idUserCreator :string;
}
