export class Commun {
  id: number;
  adminId :number;
  etabId: number;
  typeDecint: number;
  typeDecstr :string;
  userName :string;
  userId :string;
  adminName :string;
  etabName :string;
  num :string;
  position :string;
  emploi :string;
  dateTravail :string;
  infraction :string;
  dateFinContratHij :string;
  dateFinContratMil :string;
  raison :string;
  autre :string;
  attribut1: number;
  attribut2 :string;
  attribut3 :string;
  attribut4 :string;
  attribut5 :string;
  attribut6 :string;
  dateenreg :string;
  userNameCreator :string;
  idUserCreator :string;
}
