export class Musulman {
  id: number;
  numdos: string;
  predicateur : string;
  prevnom : string;
  nvnom : string;
  engnom: string;
  datehij: string;
  datemil : string;
  jours : string;
  nat : string;
  langue : string;
  residence : string;
  dateresidence: string;
  sourceres : string;
  religion : string;
  numpass : string;
  datepass : string;
  sourcepass : string;
  datenais : string;
  travail : string;
  cite : string;
  adr : string;
  telmus : string;
   urlsm: string;
  garantnom : string;
  garanttype : string;
   registre: string;
  telgarant : string;
  files : string;
  pub  : string;
  scene : string;
   test: string;
  cadeauxtest : string;
  recep : string;
  change : string;
   soiree: string;
  circonsion : string;
  omra : string;
  city : string;
  walking : string;
  haj : string;
  depart : string;
  chatdep : string;
  req : string;
attribut1: number;
  attribut2 : string;
  attribut3 : string;
  attribut4 : string;
  attribut5 : string;
  attribut6 : string;
  dateenreg : string;
  usernamecreator : string;
  idusercreator : string;
}
