export class CrationTravailDemande {
  id: number;
  transferera : string;
     transfertetab : string;
     transfertrh : string;
     transfertdeux : string;
     datetransfert : string;
     idtrh : string;
     idtetab : string;
     nomtrh : string;
     nomtetab : string;
     etattrh : string;
     etatetab : string;
     datetrh : string;
     dateetab : string;
     tran1 : string;
     tran2 : string;
     tran3 : string;
     tran4 : string;
     tran5 : string;
     tran6 : string;
  username:string;
  titreposte:string;
  selection:string;
  tacheTravail:string;
  competence:string;
  diplome:string;
  datedebut:string;
  iddir :string;
  nomdir :string;
  datedir :string;
  etatdir  :string;
  etat :string;
  idrh :string;
  etatrh:string;
  nomrh :string;
  daterh :string;
  datedg :string;
  etatdg :string;
  iddg:string;
  nomdg:string;
  attribut1: number;
  attribut2 :string;
  attribut3 :string;
  attribut4 :string;
  attribut5 :string;
  attribut6 :string;
  dateenreg :string;
  userNameCreator :string;
  idUserCreator :string;
}
