export class DemPayCheque {
 id: number;
 calsse :string;
 dateEntre :string;
 demandeur :string;
 numdem: number;
 numdemnb :string;
 iddemandeur :string;
 description :string;
 sujet :string;
 prixnb :string;
 prixlettre :string;
 prixaccepte :string;
 etatnum :string;
 etatgeneral :string;
 etatadmin :string;
 etatdirecteur :string;
 etatfinacier :string;
 etatparfinancier :string;
 etatpart :string;
 idadmin :string;
 iddir :string;
 idfinancier :string;
 idparfinancier :string;
 idpart :string;
 nomadmin :string;
 nomdir :string;
 nomfinancier :string;
 nomparfinancier :string;
 nompart :string;
 dateadmin :string;
 datedir :string;
 datefinancier :string;
 dateparfinancier :string;
 datepart :string;
  retour :string;
 prixRetour :string;
  transfert :string;
  dateRetour :string;
  etatRetourBoxMen :string;
  etatRetourComptable :string;
  fileRetour :string;
 attribut5 :string;
 attribut6 :string;
 creatorName :string;
 dateenreg :string;
  idUserCreator: string;
  etat: string;
  userName1: string; userId1: string; userEtat1: string; userDate1: string;
  userName2: string; userId2: string; userEtat2: string; userDate2: string;
  userName3: string; userId3: string; userEtat3: string; userDate3: string;
  userName4: string; userId4: string; userEtat4: string; userDate4: string;
  userName5: string; userId5: string; userEtat5: string; userDate5: string;
  userName6: string; userId6: string; userEtat6: string; userDate6: string;
  userName7: string; userId7: string; userEtat7: string; userDate7: string;
  userName8: string; userId8: string; userEtat8: string; userDate8: string;
}
