export class Avance {
  id: number;
  transferera :string;
        transfertetab :string;
        transfertrh :string;
        transfertdeux :string;
        datetransfert :string;
        idtrh :string;
        idtetab :string;
        nomtrh :string;
        nomtetab :string;
        etattrh :string;
        etatetab :string;
        datetrh :string;
        dateetab :string;
        tran1 :string;
        tran2 :string;
        tran3 :string;
        tran4 :string;
        tran5 :string;
        tran6 :string;
prix :string;
etatAvance :string;
detail :string;
nbMoisDeduire :string;
mois :string;
annee :string;
dateDeduire :string;
etatC :string;
idC :string;
nomC :string;
dateC :string;
raisonRefusC :string;
idD :string;
etatD :string;
nomD :string;
dateD :string;
raisonRefusD :string;
attribut1: number;
attribut2 :string;
attribut3 :string;
attribut4 :string;
attribut5 :string;
attribut6 :string;
dateenreg :string;
userNameCreator :string;
  idUserCreator: string;
  etat: string;
  userName1: string; userId1: string; userEtat1: string; userDate1: string;
  userName2: string; userId2: string; userEtat2: string; userDate2: string;
  userName3: string; userId3: string; userEtat3: string; userDate3: string;
  userName4: string; userId4: string; userEtat4: string; userDate4: string;
  userName5: string; userId5: string; userEtat5: string; userDate5: string;
  userName6: string; userId6: string; userEtat6: string; userDate6: string;
  userName7: string; userId7: string; userEtat7: string; userDate7: string;
  userName8: string; userId8: string; userEtat8: string; userDate8: string;
}
