export class CreanceFinanciere {
  id: number;
date :string;
prix:string;
typePaymenet:string;
projet:string;
detail:string;
nomBeneficiaire :string;
etat:string;
etatuserId:string;
dateetatuser :string;
etatusernom:string;
etatdirectorid :string;
etatdirectornom:string;
etatdirectordate:string;
etatPayement:string;
etatPayUserId:string;
etatPayUsernom:string;
etatPayUserDate:string;
typePayement:string;
datesalaire:string;
editdate :string;
edituserId :string;
editUserNom:string;
numcompteExp:string;
numcompteRecp:string;
numcheque: string;
datePayEspece: string;
nomBanque: string;
dateCheque: string;
numCompte: string;
numCheque: string;
photocheque: string;
datepaysalaire: string;
attribut1: number;
attribut2 :string;
attribut3 :string;
attribut4 :string;
attribut5 :string;
attribut6 :string;
dateenreg :string;
userNameCreator :string;
idUserCreator :string;
}
