export class Conge {
  id: number;
 transferera :string;
  transfereretab :string;
       transfertrh :string;
       transfertdeux :string;
       datetransfert :string;
       idtrh :string;
       idtetab :string;
       nomtrh :string;
       nomtetab :string;
       etatrh :string;
       etatetab :string;
       daterh :string;
       dateetab :string;
       tran1 :string;
       tran2 :string;
       tran3 :string;
       tran4 :string;
       tran5 :string;
       tran6 :string;
  datedebut :string;
  datefin :string;
  duree :string;
  tel :string;
  type :string;
  adr:string;
  idremplacant :string;
  nomremplacant:string;
  etat :string;
  etatd :string;
  directeurid:string;
  directeurnom:string;
  rhid:string;
  rhnom :string;
  dated:string;
  attribut1: number;
  attribut2 :string;
  attribut3 :string;
  attribut4 :string;
  attribut5 :string;
  attribut6 :string;
  dateenreg :string;
  userNameCreator :string;
  idUserCreator :string;
}
