export class Recrutement {
  id: number;
 type:string;
 datedebut :string;
 datefin :string;
 dure:string;
 organisme:string;
 idremplacant:string;
 nomremplacant:string;
 tache :string;
 etatdir:string;
 etatrh:string; 
 iddir:string;
 idrh :string;
 nomrh :string;
 nomdir :string;
 daterh:string;
 dated:string;
 attribut1: number;
 attribut2 :string;
 attribut3 :string;
 attribut4 :string;
 attribut5 :string;
 attribut6 :string;
 dateenreg :string;
 userNameCreator :string;
  idUserCreator: string;
  etat: string;
  userName1: string; userId1: string; userEtat1: string; userDate1: string;
  userName2: string; userId2: string; userEtat2: string; userDate2: string;
  userName3: string; userId3: string; userEtat3: string; userDate3: string;
  userName4: string; userId4: string; userEtat4: string; userDate4: string;
  userName5: string; userId5: string; userEtat5: string; userDate5: string;
  userName6: string; userId6: string; userEtat6: string; userDate6: string;
  userName7: string; userId7: string; userEtat7: string; userDate7: string;
  userName8: string; userId8: string; userEtat8: string; userDate8: string;
}
