export class UserDetail {
        id : string;
        userName : string;
        email : string;
        Password : string;
        registreCivil : string;
        FullNameEnglish : string;
        fullName : string;
        adresse : string;
        PhoneNumber : string;
        tel : string;
        statut : string;
        nationalite : string;
        religion : string;
        sexe : string;
        dateNaissance : string;
        lieuNaissance : string;
        passeport : string;
        typeSang : string;
        num : string;
        emploi : string;
        rang : string;
        typeEmploi : string;
        nomAdministration : string;
        nomDepartement : string;
        unite : string;
        qualification : string;
        typeQualification : string;
        faculteEcole : string;
        dateQualification : string;
        specialite : string;
        paysetude : string;
        mention : string;
        classement : string;
        degre : string;
        salaire : string;
        indemnite : string;
        autreIndemnite : string;
        heureArrive : string;
        heureDepart : string;
        photo : string;
        idAdministration : number;
  idDepartement: number;
  directeur : string;
  position :string;
  attribut1 :string;
  attribut2 :string;
  attribut3 :string;
  attribut4 :string;
  attribut5 :string;
  attribut6: string;

  soldeconge :string;
        daterectrutement :string;
        etatuser :string;
        dateenreg :string;
        userNameCreator :string;
        idUserCreator :string;

}
