export class Transaction {
  id: number;
  type:string;
  date:string;
  typeRecue:string;
  priorite:string;
  securite:string;
  nomOrg:string;
  nomProp:string;
  tel:string;
  registreCivil:string;
  numAutorite:string;
  sujet:string;
  typeEmise:string;
  nomLivreur:string;
  operationlivraison:string;
  orgEnregTr:string;
  autoriteExterne:string;
  copieExterne:string;
  copieA:string;
  nbPjNumerique:string;
  nbPj:string;
  remarque:string;
  action:string;
  typeInterne:string;
  dateFinisAction:string;
  autoriteExpeditrice:string;
  dateFinis:string;
  attribut1: number;
  attribut2:string;
  attribut3:string;
  attribut4:string;
  attribut5 :string;
  attribut6:string;
  etablissementUserCreator:string;
  idEtablissementUserCreator: number;
  etat:string;
  dateenreg:string;
  userNameCreator:string;
  idlivreur: number;
  idAutoriteExterne: number;
  idOrg: number;
  idProp: number;
  idUserCreator: string;
}
