export class Retrait {
  id : string;
  nom : string;
  tel : string;
  organisme : string;
  rib : string;
  banque : string;
  idbanque: number;
  typedate : string;
  datedebuthij : string;
  datefinhij : string;
  datedebutmiledi : string;
  datefinmiledi  : string;
  nombanque : string;
  nomben : string;
  ribben : string;
  idben: number;
  typedons : string;
  prix : string;
  delegues : string;
  etat : string;
  resultat : string;
  typeRetrait  : string;
  janvier : string;
  fevrier: string;
  mars : string;
  avril : string;
  mai : string;
  juin : string;
  juillet : string;
  aout : string;
  septembre : string;
  octobre : string;
  novembre : string;
  decembre : string;      
attribut1: number;
attribut2 : string;
attribut3 : string;
attribut4 : string;
attribut5 : string;
attribut6 : string;
dateenreg : string;
userNameCreator : string;
idUserCreator : string;
}
